#!/bin/bash

VERSION=0.9.5

function assert_root {
  if [[ $EUID -ne 0 ]]; then
     echo "This script must be run as root" 
     exit 1
  fi
}

function install {
  sed -i -e "s/%VERSION%/${VERSION//\//\\/}/g" PKG-INFO
  sed -i -e "s/%VERSION%/${VERSION//\//\\/}/g" setup.py
  python ./setup.py install
}

assert_root
install
